repos:
  - repo: local
    hooks:
      - id: make-build-and-test
        name: Build and test
        entry: |
          sh -c "
          if make build; then
            git add docs && \
            make test
          else
            echo 'Build failed, skipping tests.' >&2
            exit 1
          fi
          "
        language: system
        pass_filenames: false
        always_run: true
