[tool.black]
line-length = 120
target-version = ["py312"]
exclude = """
(
    /old/
    | /dev_.*
    | /build/
    | /docs/
)
"""

[tool.isort]
profile = "black"
skip_glob = ["old", "dev_*.py", "build", "docs"]

[tool.flake8]
max-line-length = 120
extend-ignore = ["D203"]
extend-exclude = ["old/*.py", "dev_*.py", "build/*.py", "docs/*.py"]
docstring-convention = "google"

[tool.pytest.ini_options]
cache_dir = "build/.pytest_cache"
